---

- debug: var=hostvars[groups['elakibb'][0]].networkInterfaces[0].networkIP

- name: Create an user for elasticsearch
  user: 
    name: monitor
    create_home: True

- name: Install java
  apt:
    name: openjdk-8-jre
    state: present

- name: Instalação de dependências
  apt:
    name:
    - libxslt1-dev
    - wget
    - apt-transport-https
    - ntp 
    - tcpdump
    - wget
    - openssl

- name: Download do elasticsearch
  get_url:
    url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-linux-x86_64.tar.gz
    dest: /home/monitor/
  become_user: monitor

- name: Unzip do elasticsearch
  unarchive:
    src: /home/monitor/elasticsearch-7.4.2-linux-x86_64.tar.gz
    dest: /home/monitor/
    remote_src: yes
  become_user: monitor

- name: Increase vm map count
  sysctl:
    name: vm.max_map_count
    value: 262144

- name: Configure Elasticsearch network.host
  replace:
    path: "/home/monitor/elasticsearch-7.4.2/config/elasticsearch.yml"
    regexp: '^#network.host: .*'
    replace: 'network.host: 0.0.0.0'
  become_user: monitor

- name: Configure ElasticSearch discovery.seed_hosts
  replace:
    path: "/home/monitor/elasticsearch-7.4.2/config/elasticsearch.yml"
    regexp: '^#discovery.seed_hosts: .*'
    replace: 'discovery.seed_hosts: []'
  become_user: monitor

- name: Configure ElasticSearch cluster.initial_master_nodes
  replace:
    path: "/home/monitor/elasticsearch-7.4.2/config/elasticsearch.yml"
    regexp: '^#cluster.initial_master_nodes: .*'
    replace: "cluster.initial_master_nodes: [\"{{hostvars[groups['elakibb'][0]].networkInterfaces[0].networkIP}}\"]"
  become_user: monitor

#- name: Iniciar server elasticsearch
#  shell: "./elasticsearch -d"
#  args:
#    chdir: "/home/monitor/elasticsearch-7.4.2/bin/"
#  become_user: monitor