---

- name: SSH KeyGen command
  become: true
  become_user: postgres
  shell: >
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"

- name: Fetch the keyfile from the node to master
  become: true
  become_user: postgres
  tags: run
  fetch: 
    src: "~/.ssh/id_rsa.pub"
    dest: "roles/psql-ssh/files/buffer/{{ansible_hostname}}-id_rsa.pub"
    flat: yes

- name: Copy the key add to authorized_keys using Ansible module
  authorized_key:
    user: postgres
    state: present
    key: "{{ lookup('file','buffer/{{hostvars[item].name}}-id_rsa.pub')}}"
  when: "{{ hostvars[item].name != ansible_hostname }}"
  with_items: 
    - "{{ groups['be'] }}" 


- name: Copy psql configuration templates
  copy:
    src: config
    dest: /var/lib/postgresql/.ssh/config
    owner: postgres

