---

- name: Configure OpenProject 1
  copy:
    src: /home/openproject/openproject/config/database.yml.example
    dest: /home/openproject/openproject/config/database.yml
    remote_src: yes
  become: true
  become_user: openproject

- name: Config database connection
  replace:
    regexp: '^production.*\n(\s+.*\n*)*'
    path: /home/openproject/openproject/config/database.yml
    replace: "{{ lookup('template','db-conn.j2') }}"


- name: Config email connection and memcached
  copy:
    dest: /home/openproject/openproject/config/configuration.yml
    src: configuration.yml
  become: true
  become_user: openproject


## precompile vai falhar; fazer apt-get remove nodejs 

- name: Remove conflicting nodejs 
  apt:
    name: nodejs
    state: absent

# echo "export PATH=$HOME/.rbenv/shims:$PATH" >> ~/.profile &&
- name: Setup the database
  shell:
    cmd: |
         . ~/.profile &&
         echo "export SECRET_KEY_BASE=$(./bin/rake secret)" >> ~/.profile &&
         . ~/.profile &&
         echo "export SECRET_KEY_BASE=$(./bin/rake secret)" >> ~/.profile &&
         RAILS_ENV="production" ./bin/rake db:create &&
         RAILS_ENV="production" ./bin/rake db:migrate &&
         RAILS_ENV="production" ./bin/rake db:seed &&
         RAILS_ENV="production" ./bin/rake assets:precompile
    chdir: /home/openproject/openproject
  become: true
  become_user: openproject

- name: Define SECRET_KEY_BASE
  shell:
    cmd: |
         . /home/openproject/.profile &&
         echo "export SECRET_KEY_BASE=$SECRET_KEY_BASE" >> /etc/apache2/envvars
    chdir: /home/openproject/openproject

- name: chmod /home/openproject
  file:
    path: /home/openproject
    mode: o+x

- name: gem install passenger
  gem:
    name: passenger
    executable: /home/openproject/.rbenv/shims/gem
  become: true
  become_user: openproject

- name: Installing Passenger module for Apache2
  shell:
    cmd: /home/openproject/.gem/ruby/2.6.0/bin/passenger-install-apache2-module --languages 'ruby' --auto
    chdir: /home/openproject/openproject
  become: true
  become_user: openproject

- name: Copy passenger.load
  template:
    dest: /etc/apache2/mods-available/passenger.load
    src: passenger-load.j2

- name: Copy passenger.conf
  template:
    dest: /etc/apache2/mods-available/passenger.conf
    src: passenger-conf.j2

- name: Enable Apache's Passenger module
  apache2_module:
    name: passenger
    state: present

- name: Copy openproject.conf
  copy:
    dest: /etc/apache2/sites-available/openproject.conf
    src: openproject.conf

- name: Add Passenger to PATH and enable site OpenProject
  shell:
    cmd: export PATH="/home/openproject/.gem/ruby/2.6.0/gems/passenger-6.0.4/bin:$PATH" && a2dissite 000-default && a2ensite openproject

- name: Create a symbolic link
  file:
    src: /etc/apache2/mods-available/expires.load
    dest: /etc/apache2/mods-enabled/expires.load
    state: link

- name: Restart apache2
  service:
    name: apache2
    state: restarted